Link `yaml-cpp` in loadable extension to avoid missing symbols in vcpkg `.duckdb_extension` build (#649)
Required for #621.

This fixes:
```
_duckdb.IOException: IO Error: Extension "sirius.duckdb_extension" could not be loaded: sirius.duckdb_extension: undefined symbol: _ZTIN4YAML13BadConversionE
```